version: '3.3'
services:
  tomcat:
    container_name: contiene_tomcat
    hostname: tomcat
    image: drecioa/tomcat:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      mongo:
        condition: service_healthy
      dns:
        condition: service_started
    networks:
      red_integradora:
        ipv4_address: 192.168.100.4
    dns:
      - 192.168.100.254
  mysql:
    container_name: contiene_mysql
    hostname: mysql
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    depends_on:
      dns:
        condition: service_started
    networks:
      red_integradora:
        ipv4_address: 192.168.100.2
    dns:
      - 192.168.100.254
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
  mongo:
    container_name: contiene_mongo
    image: mongo:4.4.6
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    depends_on:
      - dns
    networks:
      red_integradora:
        ipv4_address: 192.168.100.3
    dns:
      - 192.168.100.254
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb://root:root@localhost:27017/?authSource=admin --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  dns:
    container_name: contiene_bind9
    hostname: bind
    image: drecioa/bind9:latest
    restart: always
    expose:
      - 53/udp
      - 53/tcp
    ports:
      - "953:953/tcp"
    networks:
      red_integradora:
        ipv4_address: 192.168.100.254
    dns:
      - 192.168.100.254
  apache:
    container_name: contiene_apache
    hostname: apache
    image: drecioa/httpd:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      dns:
        condition: service_started
      tomcat:
        condition: service_started
    networks:
      red_integradora:
        ipv4_address: 192.168.100.5
    dns:
      - 192.168.100.254
networks:
  red_integradora:
    ipam:
       config:
         - subnet: 192.168.100.0/24