spring:
  application:
    name: IntegradoraTomcat
  datasource:
    url: jdbc:mysql://192.168.100.2:3306/integradoraJPA?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: lang/messages
  jpa:
    hibernate:
     # ddl-auto: update #cuando persistamos definitivamente y dejemos de hacer pruebas
      ddl-auto: create #para que elimine la db al parar la aplicación
    database: mysql
    show-sql: true
    generate-ddl: true # esto hace que se creen las tablas
    defer-datasource-initialization: true # diferir la carga de datos (DataSource initialization)
  sql:
    init:
      mode: always # para que se cree la db al iniciar la aplicación
  data:
    mongodb:
      uri: mongodb://root:root@192.168.100.3:27017/tienda?authSource=admin
      username: root
      password: root