spring:
  application:
    name: IntegradoraTomcat
  datasource:
    url: jdbc:mysql://192.168.7.10:5580/integradoraJPA?createDatabaseIfNotExist=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
#    name: integradoraJPA # este es el nombre de la base de datos
  jpa:
    hibernate:
#      ddl-auto: update #cuando persistamos definitivamente y dejemos de hacer pruebas
      ddl-auto: create-drop #para que elimine la db al parar la aplicación
    database: mysql
    show-sql: true
    generate-ddl: true # esto hace que se creen las tablas
    defer-datasource-initialization: true # diferir la carga de datos (DataSource initialization)
  sql:
    init:
      mode: always # para que se cree la db al iniciar la aplicación
  data:
    mongodb:
      uri: mongodb://192.168.7.10:27017/tienda?createDatabaseIfNotExist=true