spring:
  application:
    name: IntegradoraTomcat
  datasource:
    url: jdbc:mysql://mysql.da2.dva:3306/integradoraJPA?createDatabaseIfNotExist=true #Despliegue
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: lang/messages
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    generate-ddl: true
  data:
    mongodb:
      uri: mongodb://root:root@mongo.da2.dva:27017/tienda?authSource=admin  #Despliegue
      username: root
      password: root